---

version: "2"

volumes:
  mysqlData:
    driver: local

services:
  webserver:
    image: "nginx:1.11"
    links:
      - "php"
    volumes:
      - "./Build/docker/nginx.conf:/etc/nginx/nginx.conf"
      - "./:/var/www/"
      - "./logs/webserver/:/var/log/nginx/"
    env_file:
      - "./.env"
    environment:
      VIRTUAL_HOST: "${HOSTNAME}"
      VIRTUAL_PORT: 80
  php:
    image: "larsnieuwenhuizen/php"
    command: "php-fpm7.0 -F"
    working_dir: "/var/www/"
    env_file:
      - "./.env"
    links:
      - "db"
    volumes:
      - "./Build/docker/php-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf"
      - "./Build/docker/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Build/docker/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "./:/var/www/"
  db:
    image: "mariadb"
    env_file:
      - "./.env"
    volumes:
      - "mysqlData:/var/lib/mysql"
      - "./../logs/db/:/var/log/mysql/"
      - "./Build/docker/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
    ports:
      - "33${PORTSUFFIX}:3306"
  composer:
    image: "composer/composer:alpine"
    working_dir: "/app/"
    volumes:
      - "./:/app/"
      - "~/.composer/:/composer/"
    env_file:
      - "./.env"
  symfony:
    image: "larsnieuwenhuizen/symfony-installer"
    working_dir: "/app/"
    volumes:
      - "./:/app/"
    env_file:
      - "./.env"
  laravel:
    image: "larsnieuwenhuizen/laravel-installer"
    working_dir: "/app/"
    volumes:
      - "./:/app/"
    env_file:
      - "./.env"
  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "${MAILCATCHER_HOSTNAME}"
      VIRTUAL_PORT: 1080
  elasticsearch:
    image: "elasticsearch:2.4"
    env_file:
      - "./.env"
    ports:
      - "92${PORTSUFFIX}:9200"
      - "93${PORTSUFFIX}:9300"
    environment:
      VIRTUAL_HOST: "${ELASTICSEARCH_HOSTNAME}"
      VIRTUAL_PORT: 9200
